version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy
      - cmd: cargo +nightly clippy --all-targets

  cov:
    desc: Generates the code coverage report
    cmds:
      - cmd: cargo llvm-cov --quiet --no-cfg-coverage --no-cfg-coverage-nightly --workspace --html
      - cmd: echo -e "\nOpen report file:///$(pwd)/target/llvm-cov/html/index.html\n"

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  test:
    desc: Tests in debug mode for all settings
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Tests in debug mode for all settings using nextest
    cmds:
      - cmd: cargo +stable nextest run
