version: '3'

silent: true

tasks:

  build000:
    desc: Builds in debug mode with settings 000
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy000:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --all-targets

  cov:
    desc: Runs code coverage using grcov
    cmds:
      - cmd: ./coverage.sh

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  test000:
    desc: Tests in debug mode
    cmds:
      - cmd: cargo +stable test
